version: '3.8'


services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - fast-api-network

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - fast-api-network

networks:
  fast-api-network: